<?php

declare(strict_types=1);

function oflc_get_one_year_logic_keys(): array
{
    return [
        1 => [0 => 'advent_1'],
        2 => [0 => 'advent_2'],
        3 => [0 => 'advent_3'],
        4 => [0 => 'advent_4'],
        5 => [0 => 'sunday_after_christmas'],
        6 => [0 => 'sunday_after_new_years'],
        7 => [0 => 'baptism_of_our_lord'],
        8 => [0 => 'epiphany_2'],
        9 => [0 => 'epiphany_3'],
        10 => [0 => 'epiphany_4'],
        11 => [0 => 'epiphany_5'],
        12 => [0 => 'transfiguration'],
        13 => [0 => 'septuagesima'],
        14 => [0 => 'sexagesima'],
        15 => [0 => 'quinquagesima', 3 => 'ash_wednesday'],
        16 => [0 => 'lent_1'],
        17 => [0 => 'lent_2'],
        18 => [0 => 'lent_3'],
        19 => [0 => 'lent_4'],
        20 => [0 => 'lent_5'],
        21 => [
            0 => ['palm_sunday_procession', 'passion_sunday'],
            1 => 'holy_week_monday',
            2 => 'holy_week_tuesday',
            3 => 'holy_week_wednesday',
            4 => 'maundy_thursday',
            5 => 'good_friday',
            6 => 'holy_saturday',
        ],
        22 => [
            0 => ['easter_dawn', 'easter_day'],
            1 => 'easter_monday',
            2 => 'easter_tuesday',
            3 => 'easter_wednesday',
        ],
        23 => [0 => 'easter_2'],
        24 => [0 => 'easter_3'],
        25 => [0 => 'easter_4'],
        26 => [0 => 'easter_5'],
        27 => [0 => 'easter_6', 4 => 'ascension'],
        28 => [0 => 'easter_7'],
        29 => [0 => ['pentecost_eve', 'pentecost_day'], 1 => 'pentecost_evening_monday', 2 => 'pentecost_tuesday'],
        30 => [0 => 'trinity_sunday'],
        31 => [0 => 'trinity_1'],
        32 => [0 => 'trinity_2'],
        33 => [0 => 'trinity_3'],
        34 => [0 => 'trinity_4'],
        35 => [0 => 'trinity_5'],
        36 => [0 => 'trinity_6'],
        37 => [0 => 'trinity_7'],
        38 => [0 => 'trinity_8'],
        39 => [0 => 'trinity_9'],
        40 => [0 => 'trinity_10'],
        41 => [0 => 'trinity_11'],
        42 => [0 => 'trinity_12'],
        43 => [0 => 'trinity_13'],
        44 => [0 => 'trinity_14'],
        45 => [0 => 'trinity_15'],
        46 => [0 => 'trinity_16'],
        47 => [0 => 'trinity_17'],
        48 => [0 => 'trinity_18'],
        49 => [0 => 'trinity_19'],
        50 => [0 => 'trinity_20'],
        51 => [0 => 'trinity_21'],
        52 => [0 => 'trinity_22'],
        53 => [0 => 'trinity_23'],
        54 => [0 => 'trinity_24'],
        55 => [0 => 'third_last_sunday'],
        56 => [0 => 'second_last_sunday'],
        57 => [0 => 'last_sunday'],
    ];
}

function oflc_get_fixed_logic_keys(): array
{
    return [
        '1-1' => 'circumcision_and_name_of_jesus',
        '1-6' => 'epiphany',
        '1-18' => 'confession_of_saint_peter',
        '1-24' => 'saint_timothy',
        '1-25' => 'conversion_of_saint_paul',
        '1-26' => 'saint_titus',
        '2-2' => 'presentation_of_our_lord',
        '2-24' => 'saint_matthias',
        '3-19' => 'saint_joseph',
        '3-25' => 'annunciation',
        '4-25' => 'saint_mark',
        '5-1' => 'saint_philip_and_saint_james',
        '6-11' => 'saint_barnabas',
        '6-24' => 'nativity_of_john_the_baptist',
        '6-29' => 'saint_peter_and_saint_paul',
        '7-2' => 'visitation',
        '7-22' => 'saint_mary_magdalene',
        '7-25' => 'saint_james_the_elder',
        '8-15' => 'saint_mary_mother_of_our_lord',
        '8-24' => 'saint_bartholomew',
        '8-29' => 'martyrdom_of_saint_john_the_baptist',
        '9-14' => 'holy_cross_day',
        '9-21' => 'saint_matthew',
        '9-29' => 'saint_michael_and_all_angels',
        '10-18' => 'saint_luke',
        '10-23' => 'saint_james_of_jerusalem',
        '10-28' => 'saint_simon_and_saint_jude',
        '10-31' => 'reformation_day',
        '11-1' => 'all_saints_day',
        '11-30' => 'saint_andrew',
        '12-21' => 'saint_thomas',
        '12-24' => ['christmas_eve_early', 'christmas_midnight'],
        '12-25' => ['christmas_dawn', 'christmas_day'],
        '12-26' => 'saint_stephen',
        '12-27' => 'saint_john_apostle_and_evangelist',
        '12-28' => 'holy_innocents',
    ];
}
